\documentclass[12pt]{article}\usepackage[]{graphicx}\usepackage[]{color}
%% maxwidth is the original width if it is less than linewidth
%% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}
\usepackage[english]{babel}
\usepackage{natbib}
\usepackage{url}
\usepackage[utf8x]{inputenc}
\usepackage{amsmath}
\usepackage{graphicx}
\graphicspath{{images/}}
\usepackage{parskip}
\usepackage{fancyhdr}
\usepackage{vmargin}
%\usepackage{filecontents}
%\usepackage[style=authoryear,backend=bibtex]{biblatex}
\usepackage[nottoc]{tocbibind}
\setmarginsrb{3 cm}{2.5 cm}{3 cm}{2.5 cm}{1.0 cm}{1.5 cm}{1.0 cm}{1.5 cm}

\setlength\lineskip{12pt}
\title{How To Make a Free Throw Shooter Miss}\par					% Title
\author{Kevin Toney, Chase Weight, Nick Mena}								% Author
\date{\today}											% Date

\makeatletter
\let\thetitle\@title
\let\theauthor\@author
\let\thedate\@date
\makeatother

\pagestyle{fancy}
\fancyhf{}
\rhead{\theauthor}
\lhead{\thetitle}
\cfoot{\thepage}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{titlepage}
	\centering
    \vspace*{0.5 cm}
    \textsc{\LARGE STAT 230 Revised Project}\\[2.0 cm]	% University Name
	\textsc{\Large STAT 290}\\[0.5 cm]				% Course Code
	\rule{\linewidth}{0.2 mm} \\[0.4 cm]
	{ \huge \bfseries \thetitle}\\
	\rule{\linewidth}{0.2 mm} \\[1.5 cm]
	
	\begin{minipage}{0.8\textwidth}
		\begin{flushleft} \large
			\emph{Author:}\\
			\theauthor
			\end{flushleft}
			\end{minipage}~
	
	{\large \thedate}\\[2 cm]
 
	\vfill
	
\end{titlepage}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\tableofcontents
\pagebreak

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\section{Abstract}
\hspace{1cm}In this study, we performed an experiment to determine what factors significantly influence the amount of free throws made by a basketball player. We decided on this experiment because we are basketball fans that regularly attend games. We were wondering how much our crowd noise and ball inflation levels mattered in a player's shooting performance. 

\hspace{1cm}The factors of interest were whether there were large amounts of noise in the room or not, and whether the basketball was fully inflated or not. Therefore, this experiment was a $2^2$ factorial design. We hypothesized that none of these factors would make a significant impact.

\hspace{1cm}We invited a group of 20 college students to participate in our study. These students varied in gender and skill, but we used a poisson distribution to account for each shooter independently. During the experiment, we assigned the students to one of four groups. One group had deflated balls with no noise, another had deflated balls with lots of noise. Then, the last two groups used inflated balls with silence, or inflated balls with lots of noise. Each student shot 20 free throws and recorded the proportion of made shots. 

\hspace{1cm}After gathering data, we performed poisson regression. At the significance level of alpha=0.05, we found shooting free throws with a different level of inflation made the only statistically significant difference. As a matter of fact, shooting with deflated balls improved the free throw percentage of a player.

\hspace{1cm}The experiment is practically significant because a team can be assured that crowd noise, alone, won't significantly impact their players at the free throw line. Other factors, which can be studied more, such as the player's emotional state, visual distractions, fatigue, or confidence level may affect their performance. Therefore, we would recommend that basketball players practice regularly on their free throw shooting and not worry about the crowd's noise.

\hspace{1cm}Now we can answer our question "What factors significantly influence a players free throw percentage?" We conclude the inflation level of the ball, not the noise level of the crowd, makes a significant impact on free throw shooting.\\



\newpage

\section{Introduction}

In this study, we performed an experiment to determine what factors significantly influence the proportion of free throws made by a basketball player.We decided on performing this experiment because we are huge basketball fans, and wanted to know if our presence made a difference in the outcome of a game. 

We were wondering how much a fan's noise mattered in the outcome of the game. Additionally, we wondered if the amount of air in a ball would make a difference. The reason why we were interested in the inflation level is because a scandal with a famous football player, named Tom Brady, accused the player of deflating footballs so he would have more control over the ball he threw. Our original hypothesis was that none of these factors made a significant impact. 

\section{Experimental Design}

We randomly split up 20 students into four groups and they had an objective to shoot 20 free throws. Each group reflected a combination of the factors of interest. For your information, these students varied in gender and skill, but we used a poisson distribution to account for each shooter independently.

The factors of interest (main effects) were whether there were large amounts of noise or not, and whether the basketball is fully inflated or not. For a table of these factors, see the figure below. We chose to test only these two factors out of the many that would influence a player's shooting. For example, a player might struggle shooting free throws because they are tired, sick, or angry. We ignored those factors for this experiment. 

\includegraphics[scale=0.33]{table_of_groups.png}

The reponse variable has a unit of makes in 20 attempts. The variable is measured in counts, thus supporting our chosen method of analysis. 

We decided to run a poisson regression for analysis. The data has a sample size of 20 for each of the 20 shooters. That sample size is enough for a poisson distribution and a poisson regression model. Each of the five people in a group will have a p-value. The central limit theorem says that for each group, 5*20 shots will help estimate p-values. 

\section{Results}

%This part of the report is very important, I can have R run code from SAS, Python, and other
%programming languages. This block runs code from separate files in your server. 
%this is the setup area

Here is the data we gathered for each of the 20 shooters. 


%if there is a tab separator, use "/t". 
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{freethrows} \hlkwb{<-} \hlkwd{read.table}\hlstd{(}\hlstr{"Free Throws.csv"}\hlstd{,} \hlkwc{header}\hlstd{=T,} \hlkwc{sep}\hlstd{=}\hlstr{","}\hlstd{)}
\hlstd{freethrows}\hlopt{$}\hlstd{Response} \hlkwb{<-} \hlstd{freethrows}\hlopt{$}\hlstd{Response}\hlopt{*}\hlnum{20}
\end{alltt}
\end{kframe}
\end{knitrout}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hlstd{(freethrows}\hlopt{$}\hlstd{Response)}
\end{alltt}
\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.00    5.75    9.50    8.80   11.00   17.00
\end{verbatim}
\end{kframe}
\end{knitrout}

% latex table generated in R 3.3.2 by xtable 1.8-2 package
% Tue May  2 08:41:49 2017
\begin{table}[ht]
\centering
\begin{tabular}{rrrr}
  \hline
Group & Response & Silence & Inflated \\ 
  \hline
  1 & 3.00 &   1 &   1 \\ 
    1 & 6.00 &   1 &   1 \\ 
    1 & 5.00 &   1 &   1 \\ 
    1 & 7.00 &   1 &   1 \\ 
    1 & 6.00 &   1 &   1 \\ 
    2 & 16.00 &   1 &   0 \\ 
    2 & 5.00 &   1 &   0 \\ 
    2 & 12.00 &   1 &   0 \\ 
    2 & 17.00 &   1 &   0 \\ 
    2 & 10.00 &   1 &   0 \\ 
    3 & 8.00 &   0 &   1 \\ 
    3 & 9.00 &   0 &   1 \\ 
    3 & 11.00 &   0 &   1 \\ 
    3 & 10.00 &   0 &   1 \\ 
    3 & 2.00 &   0 &   1 \\ 
    4 & 12.00 &   0 &   0 \\ 
    4 & 10.00 &   0 &   0 \\ 
    4 & 11.00 &   0 &   0 \\ 
    4 & 11.00 &   0 &   0 \\ 
    4 & 5.00 &   0 &   0 \\ 
   \hline
\end{tabular}
\caption{The response variable is the amount of free throw makes in 20 attempts. In the 'Silence' and 'Inflated' columns, a one means 'Yes' and a zero means 'No'.} 
\label{tab:ldsl}
\end{table}

According to our results, group two had the highest free throw percentage. This group shot in silence and used a underinflated ball. 

\section{Analysis}

Here are the boxplots showing how each group's data relates to each other. 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/analysis_graphics-1} 

\includegraphics[width=\maxwidth]{figure/analysis_graphics-2} 

\end{knitrout}
You can see that the variances of each group are not similar. We made a log transformation to the data so the data had variances that were more alike. 



Furthermore, we found an apparent interaction between noise and inflation. The interaction graphs are below. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}
\includegraphics[width=\maxwidth]{figure/interactions-1} 

\end{knitrout}

I performed a poisson regression model to compare the average amount of shots made per player. If we do regression for all three factors, the degrees of freedom is 16. Using this model, we looked at a chi square of 1.2. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{#anova test on a log transformation}
\hlkwd{anova}\hlstd{(}\hlkwd{lm}\hlstd{(logsurv}\hlopt{~}\hlstd{Inflated}\hlopt{+}\hlstd{Silence}\hlopt{+}\hlstd{Inflated}\hlopt{*}\hlstd{Silence,} \hlkwc{data}\hlstd{=freethrows))}
\end{alltt}
\begin{verbatim}
## Analysis of Variance Table
## 
## Response: logsurv
##                  Df Sum Sq Mean Sq F value  Pr(>F)  
## Inflated          1 1.3980 1.39798  5.7439 0.02911 *
## Silence           1 0.0194 0.01939  0.0797 0.78134  
## Inflated:Silence  1 0.2515 0.25151  1.0334 0.32449  
## Residuals        16 3.8941 0.24338                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}
\begin{alltt}
\hlcom{#anova(lm(freethrows$Response~Inflation+Noise+Inflation*Noise, data=freethrows))}

\hlcom{#TukeyHSD(aov(lm(logsurv ~ Group, data=freethrows)))}

\hlcom{#try running a poisson regression}
\hlcom{#I am running GLM on the regular data, not log transformations}

\hlcom{#null deviance is the base model. }
\hlcom{#16 degrees of freedom come after taking the three factors. }
\hlcom{#3 degree of freedom and a chi square of 1.2. }

\hlstd{reg_pois1} \hlkwb{<-} \hlkwd{glm}\hlstd{(freethrows}\hlopt{$}\hlstd{Response}\hlopt{*}\hlnum{20}\hlopt{~}\hlstd{Inflated}\hlopt{+}\hlstd{Silence}\hlopt{+}\hlstd{Inflated}\hlopt{*}\hlstd{Silence,}
                \hlkwc{family}\hlstd{=poisson,} \hlkwc{data}\hlstd{=freethrows)}
\hlkwd{summary}\hlstd{(reg_pois1)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## glm(formula = freethrows$Response * 20 ~ Inflated + Silence + 
##     Inflated * Silence, family = poisson, data = freethrows)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5406  -0.2794   0.2536   0.6633   1.3574  
## 
## Coefficients:
##                    Estimate Std. Error z value Pr(>|z|)    
## (Intercept)          2.2824     0.1429  15.977   <2e-16 ***
## Inflated1           -0.2029     0.2131  -0.952   0.3409    
## Silence1             0.2025     0.1925   1.052   0.2929    
## Inflated1:Silence1  -0.5956     0.3148  -1.892   0.0585 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 35.945  on 19  degrees of freedom
## Residual deviance: 22.174  on 16  degrees of freedom
## AIC: 108.53
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff} \hlkwb{<-} \hlnum{35.945} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff,} \hlkwc{df}\hlstd{=}\hlnum{3}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.003234027
\end{verbatim}
\begin{alltt}
\hlkwd{predict.glm}\hlstd{(reg_pois1,} \hlkwc{type} \hlstd{=} \hlstr{"link"}\hlstd{)}
\end{alltt}
\begin{verbatim}
##        1        2        3        4        5        6        7        8 
## 1.686399 1.686399 1.686399 1.686399 1.686399 2.484907 2.484907 2.484907 
##        9       10       11       12       13       14       15       16 
## 2.484907 2.484907 2.079442 2.079442 2.079442 2.079442 2.079442 2.282382 
##       17       18       19       20 
## 2.282382 2.282382 2.282382 2.282382
\end{verbatim}
\begin{alltt}
\hlcom{#The counts are not the same = conclusion. }
\hlcom{#use the counts because they have more variability n*p*q. }


\hlstd{reg_pois2} \hlkwb{<-} \hlkwd{glm}\hlstd{(freethrows}\hlopt{$}\hlstd{Response}\hlopt{*}\hlnum{20}\hlopt{~}\hlstd{Inflated}\hlopt{+}\hlstd{Silence,}
                \hlkwc{family}\hlstd{=poisson,} \hlkwc{data}\hlstd{=freethrows)}
\hlkwd{summary}\hlstd{(reg_pois2)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## glm(formula = freethrows$Response * 20 ~ Inflated + Silence, 
##     family = poisson, data = freethrows)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.16130  -0.39995  -0.00719   0.54598   1.74705  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  2.40006    0.12136  19.776  < 2e-16 ***
## Inflated1   -0.48666    0.15524  -3.135  0.00172 ** 
## Silence1    -0.02273    0.15077  -0.151  0.88017    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 35.945  on 19  degrees of freedom
## Residual deviance: 25.802  on 17  degrees of freedom
## AIC: 110.16
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_2} \hlkwb{<-} \hlnum{25.802} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_2,} \hlkwc{df}\hlstd{=}\hlnum{2}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.1630008
\end{verbatim}
\begin{alltt}
\hlcom{#The interaction and the main effects are significant. }


\hlstd{reg_pois3} \hlkwb{<-} \hlkwd{glm}\hlstd{(freethrows}\hlopt{$}\hlstd{Response}\hlopt{*}\hlnum{20}\hlopt{~}\hlstd{Inflated,}
                \hlkwc{family}\hlstd{=poisson,} \hlkwc{data}\hlstd{=freethrows)}
\hlkwd{summary}\hlstd{(reg_pois3)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## glm(formula = freethrows$Response * 20 ~ Inflated, family = poisson, 
##     data = freethrows)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.13639  -0.37936   0.03024   0.57635   1.70626  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  2.38876    0.09578  24.939  < 2e-16 ***
## Inflated1   -0.48666    0.15524  -3.135  0.00172 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 35.945  on 19  degrees of freedom
## Residual deviance: 25.825  on 18  degrees of freedom
## AIC: 108.19
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_3} \hlkwb{<-} \hlnum{25.825} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_3,} \hlkwc{df}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.05603556
\end{verbatim}
\begin{alltt}
\hlstd{reg_pois4} \hlkwb{<-} \hlkwd{glm}\hlstd{(freethrows}\hlopt{$}\hlstd{Response}\hlopt{*}\hlnum{20}\hlopt{~}\hlstd{Silence,}
                \hlkwc{family}\hlstd{=poisson,} \hlkwc{data}\hlstd{=freethrows)}
\hlkwd{summary}\hlstd{(reg_pois4)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## glm(formula = freethrows$Response * 20 ~ Silence, family = poisson, 
##     data = freethrows)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7979  -1.0687   0.1975   0.6786   2.4852  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  2.18605    0.10600  20.623   <2e-16 ***
## Silence1    -0.02273    0.15076  -0.151     0.88    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 35.945  on 19  degrees of freedom
## Residual deviance: 35.922  on 18  degrees of freedom
## AIC: 118.28
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_4} \hlkwb{<-} \hlnum{35.922} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_4,} \hlkwc{df}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0002090433
\end{verbatim}
\begin{alltt}
\hlcom{#I am trying the predict function for a glm object}
\hlcom{#What are the results telling me? }


\hlcom{#I'll also try the linear model for log transformed data.}

\hlcom{#the difference from when we threw out the interaction (25.802 - 22.174) is not}
\hlcom{#significantly different}
\hlcom{#The difference from when we threw out the inflaction factor is 35.922. }
\hlcom{#There is a significant difference in that factor.}
\hlcom{#the difference from the base model of 22.174 and when we threw out noise, is }
\hlcom{#not statistically significant. 25.825-22.174 isn't a difference. }
\end{alltt}
\end{kframe}
\end{knitrout}

\section{Conclusion}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{pois_diff} \hlkwb{<-} \hlnum{35.945} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff,} \hlkwc{df}\hlstd{=}\hlnum{3}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.003234027
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_2} \hlkwb{<-} \hlnum{25.802} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_2,} \hlkwc{df}\hlstd{=}\hlnum{2}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.1630008
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_3} \hlkwb{<-} \hlnum{25.825} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_3,} \hlkwc{df}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.05603556
\end{verbatim}
\begin{alltt}
\hlstd{pois_diff_4} \hlkwb{<-} \hlnum{35.922} \hlopt{-} \hlnum{22.174}
\hlnum{1} \hlopt{-} \hlkwd{pchisq}\hlstd{(pois_diff_4,} \hlkwc{df}\hlstd{=}\hlnum{1}\hlstd{)}
\end{alltt}
\begin{verbatim}
## [1] 0.0002090433
\end{verbatim}
\end{kframe}
\end{knitrout}

The difference from when we threw out the inflaction factor (35.922), is a significant difference from the model resulting from all three factors (22.174). The difference from the model of 25.802, when we threw out noise, is not significant enough if it's compared to the model with all factors (22.174). The interaction is also not statistically significant. 

Therefore, only the inflation levels in the ball make a statistically significant difference on the amount of made free throws by a free throw shooter after 20 attempts. 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{predict.glm}\hlstd{(reg_pois1,} \hlkwc{type} \hlstd{=} \hlstr{"link"}\hlstd{)}
\end{alltt}
\begin{verbatim}
##        1        2        3        4        5        6        7        8 
## 1.686399 1.686399 1.686399 1.686399 1.686399 2.484907 2.484907 2.484907 
##        9       10       11       12       13       14       15       16 
## 2.484907 2.484907 2.079442 2.079442 2.079442 2.079442 2.079442 2.282382 
##       17       18       19       20 
## 2.282382 2.282382 2.282382 2.282382
\end{verbatim}
\end{kframe}
\end{knitrout}

Now, does the statistically significant factor have a practical significance? The predict.glm function helped me determine practical significance. The predict function gave four different amounts of made free throws. I looked at these four different results (1.6864, 2.4849, 2.0794, 2.2824) and compared them to each other.

In my opinion, the difference between the null model (1.6864) and the inflation factor (2.4849) is big enough (0.7985) to be practically significant. I believe this is true because that difference would be a four percent difference in a shooter's free throw percentage. However, the difference between the null model (1.6864) and the interaction factor (2.2824), which is 0.5960 is not big enough to be practically significant. 

Finally, my research concludes that basketball players will not be affected enough by crowd noise alone or by the interaction of noise and inflation. When players practice free throw shooting, they will need to worry about other factors, such as the inflation levels of the ball, their health, their confidence level, or their emotional state. 
\\


%take this code

%take the above code

\bibliographystyle{plain}
\bibliography{biblist}
%\printbibliography
%\cite{babel}, \cite{natbib}, \cite{inputenc}, \cite{url}, \cite{amsmath}, \cite{graphicx},
%\cite{parskip}, \cite{fancyhdr}, \cite{vmargin}, \cite{knitr}, \cite{ggplot2}, \cite{xtable}

\end{document}
