\documentclass[ignorenonframetext,]{beamer}
\setbeamertemplate{caption}[numbered]
\setbeamertemplate{caption label separator}{: }
\setbeamercolor{caption name}{fg=normal text.fg}
\beamertemplatenavigationsymbolsempty
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\else % if luatex or xelatex
\ifxetex
\usepackage{mathspec}
\else
\usepackage{fontspec}
\fi
\defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
\usetheme{Singapore}
\usecolortheme{rose}
\usefonttheme{serif}
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\newif\ifbibliography
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{fontsize=\small, commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\linespread{1}}{}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight0.8\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}

% Prevent slide breaks in the middle of a paragraph:
\widowpenalties 1 10000
\raggedbottom

\AtBeginPart{
\let\insertpartnumber\relax
\let\partname\relax
\frame{\partpage}
}
\AtBeginSection{
\ifbibliography
\else
\let\insertsectionnumber\relax
\let\sectionname\relax
\frame{\sectionpage}
\fi
}
\AtBeginSubsection{
\let\insertsubsectionnumber\relax
\let\subsectionname\relax
\frame{\subsectionpage}
}

\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}

\title{How to Make a Free Throw Shooter Miss}
\author{Kevin Toney}
\date{April 13, 2017}

\begin{document}
\frame{\titlepage}

\begin{frame}
\tableofcontents[hideallsubsections]
\end{frame}

\section{Research Question \&
Background}\label{research-question-background}

\begin{frame}{Questions}

\begin{itemize}
\tightlist
\item
  What factors influence a player's free throw percentage for good or
  for bad?
\item
  Does crowd noise make a difference?
\item
  Do inflation levels make an impact?
\end{itemize}

\end{frame}


\section{Experimental Design}\label{experimental-design}

\begin{frame}{Experimental Design}

\begin{itemize}
\tightlist
\item
  Response Variable: Free throw makes
  
\vspace{12pt}  

\item
  2x2 Basic Factorial Design
\item
  Factor 1: Crowd Noise
\item
  Factor 2: An Inflated or Deflated Ball
\item
  Control: Shooting free throws without noise and with an inflated ball
\end{itemize}

\end{frame}

\begin{frame}{Statistical Model}

\begin{itemize}
\item We used the following statistical model to design our experiment:
\item $x_{ijk} = \mu + Noise_j + Inflation_j + Interaction_{jk} + \epsilon_{ijk}$
\begin{itemize}
\item $x_{ijk}$ = observed made shots for individual i
\item µ = the mean shots made for each student
\item $Silence_j$ = effect due to j th level of “Silence" factor
\item $Inflated_k$ = effect due to kth level of “Inflated" factor
\item $Interaction_{jk}$ = effect due to interaction between levels j and k
\item $\epsilon_{ijk}$ = random error associated with individual i
\end{itemize}
\end{itemize}

\end{frame}

\begin{frame}{The Experiment}

\begin{itemize}
\tightlist
\item
  We asked 20 people to shoot 20 free throws.
\item
  Before they shot the free throws, we separated them, with the help of
  a random number generator, into four different groups. Each group
  represented a different situation. Each situation is shown in the
  table below.
\end{itemize}

\includegraphics{table_of_groups.png}

\end{frame}

\begin{frame}{Precautions Against Confounding Variables}

\begin{itemize}
\tightlist
\item
  The response variable (free throws made in 20 attempts) 
  follows a poisson distribution to make each shooter
  independent of each other. Therefore, the confounding variables wouldn't significantly affect the analysis. 
\end{itemize}

\end{frame}


\section{Results}\label{results}

\begin{frame}{The Experiment's Results}

\begin{center}
\includegraphics{results_table.png}
\end{center}

\end{frame}

\section{Analysis}\label{analysis}

%\begin{frame}{Notes for Reference}

%\begin{itemize}
%\tightlist
%\item
  %The variances of each group are not similar. In order to run and ANOVA
  %regression model, we made a log transformation to the data so the data
  %had variances that were more alike.
%\item
  %We found an interaction between noise and inflation.
%\end{itemize}

%\end{frame}

\begin{frame}{The Interaction Plots}

\begin{center}
\includegraphics{interaction.png}
\end{center}

\end{frame}

\begin{frame}{Method of Analysis}

\begin{itemize}
\tightlist
\item
  We performed a poisson regression model to compare the average amount
  of shots made per player. If we do regression for all factors and the interaction, the degrees of freedom is 16.
%\item
  %In poisson regression, the null deviance is the base model.
\end{itemize}

\end{frame}

\begin{frame}{Poisson Analysis Results}

  \includegraphics{poisson_results.png}

\end{frame}

\begin{frame}[fragile]{Significant Findings}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pois_diff <-}\StringTok{ }\FloatTok{35.945} \NormalTok{-}\StringTok{ }\FloatTok{22.174}
\DecValTok{1} \NormalTok{-}\StringTok{ }\KeywordTok{pchisq}\NormalTok{(pois_diff, }\DataTypeTok{df =} \DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.003234027 = Impact of all the Factors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pois_diff_2 <-}\StringTok{ }\FloatTok{25.802} \NormalTok{-}\StringTok{ }\FloatTok{22.174}
\DecValTok{1} \NormalTok{-}\StringTok{ }\KeywordTok{pchisq}\NormalTok{(pois_diff_2, }\DataTypeTok{df =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1630008 = Impact of the Interaction
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pois_diff_3 <-}\StringTok{ }\FloatTok{25.825} \NormalTok{-}\StringTok{ }\FloatTok{22.174} 
\DecValTok{1} \NormalTok{-}\StringTok{ }\KeywordTok{pchisq}\NormalTok{(pois_diff_3, }\DataTypeTok{df =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5603556 = Impact of the Silence Factor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pois_diff_4 <-}\StringTok{ }\FloatTok{35.922} \NormalTok{-}\StringTok{ }\FloatTok{22.174} 
\DecValTok{1} \NormalTok{-}\StringTok{ }\KeywordTok{pchisq}\NormalTok{(pois_diff_4, }\DataTypeTok{df =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0002090433 = Impact of the Inflated Factor
\end{verbatim}

\end{frame}

\begin{frame}
\begin{itemize}
\tightlist
\item
  The inflation levels in the ball made a statistically significant difference on the amount of
  made free throws by a free throw shooter after 20 attempts.
\end{itemize}
\end{frame}

\section{Conclusions}\label{conclusions}

\begin{frame}[fragile]{Practical Significance}

\begin{itemize}
\tightlist
\item The predict.glm function helped find practical significance.
\end{itemize}

\begin{verbatim}
##        1        2        3        4
          1.686399  1.686399 1.686399 1.686399
5        6        7        8 
1.686399 2.484907 2.484907 2.484907 
##        9        10        11        12      
          2.484907 2.484907 2.079442 2.079442
## 13       14       15       16 
  2.079442 2.079442 2.079442 2.282382 
##       17        18        19        20 
        2.282382   2.282382  2.282382  2.282382
\end{verbatim}

\begin{itemize}
\tightlist
\item
  I believe the difference between the null model (1.6864) and the
  inflation factor (2.4849) is big enough (0.7985) to be practically
  significant. This is true because the difference would be 
  four percent in a shooter's free throw percentage.
\end{itemize}

\end{frame}

\begin{frame}{Conclusion}

\begin{itemize}
\tightlist
\item
  Finally, my research concludes that basketball players will not be
  affected enough by crowd noise alone or by the interaction of noise
  and inflation.A basketball player, though would be significantly influenced by
  the inflation levels of the ball. 
\end{itemize}

\end{frame}

\begin{frame}{}

\begin{center}
\textbf{Questions?}
\end{center}

\end{frame}

\end{document}
